Update build-and-push-docker-hub.yaml

diff --git a/.github/workflows/build-and-push-docker-hub.yaml b/.github/workflows/build-and-push-docker-hub.yaml
--- a/.github/workflows/build-and-push-docker-hub.yaml
+++ b/.github/workflows/build-and-push-docker-hub.yaml
@@ -21,18 +21,18 @@ jobs:
       VERSION: ${{ github.ref_name }}
       SHA: ${{ github.sha }}
     steps:
-      - id: version_step
-        run: |
-          set -Eeuo pipefail
-          IFS=$'\n\t'
+    - id: version_step
+      run: |
+        set -Eeuo pipefail
+        IFS=$'\n\t'
 
-          if [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)(\.[0-9]+)?)?$ ]]; then
-            echo "Valid version: $VERSION"
-            echo "tags=latest,$VERSION,$SHA" >> "$GITHUB_OUTPUT"
-          else
-            echo "Invalid ref_name format: $VERSION" >&2
-            exit 1
-          fi
+        if [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)(\.[0-9]+)?)?$ ]]; then
+          echo "Valid version: $VERSION"
+          echo "tags=latest,$VERSION,$SHA" >> "$GITHUB_OUTPUT"
+        else
+          echo "Invalid ref_name format: $VERSION" >&2
+          exit 1
+        fi
 
   build_push:
     uses: zcash/.github/.github/workflows/build-and-push-docker-hub.yaml@main
